---
- hosts: all
  vars:
    nagios_download_dir: /tmp
    nagios_src: "{{ nagios_download_dir }}/nagios-4.4.6"
    nagios_src_url: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.6.tar.gz
    apache2_port: 8080
  pre_tasks:
    - name: "Update apt cache"
      apt:
        update_cache: true
        cache_valid_time: 36000
  tasks:
    - name: Install required packages
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - unzip
        - apache2

    - name: Download and unpack Nagios
      unarchive:
        src: "{{ nagios_src_url }}"
        dest: "{{ nagios_download_dir }}"
        creates: "{{ nagios_src }}"
        remote_src: yes
    - name: Run Nagios autoconf
      shell: ./configure --with-httpd-conf=/etc/apache2/sites-enabled
      args:
        chdir: "{{ nagios_src }}"
        creates: "{{ nagios_src }}/Makefile"

    - name: Make apache listen on the right port
      become: true
      block:
        - lineinfile:
            dest: /etc/apache2/ports.conf
            regexp: "^Listen 80"
            line: "Listen {{ apache2_port }}"
        - lineinfile:
            dest: /etc/apache2/sites-available/000-default.conf
            regexp: "<VirtualHost \\*:80>"
            line: "<VirtualHost *:{{ apache2_port }}>"
        - service:
            name: apache2
            state: restarted
            enabled: true


