---
- hosts: all
  vars:
    nagios_download_dir: /tmp
    nagios_src: "{{ nagios_download_dir }}/nagios-4.4.6"
    nagios_src_url: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.6.tar.gz
  pre_tasks:
    - name: "Update apt cache"
      apt:
        update_cache: true
        cache_valid_time: 36000
  tasks:
    - name: Install required packages
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - unzip
        - apache2

    - name: Download and unpack Nagios
      unarchive:
        src: "{{ nagios_src_url }}"
        dest: "{{ nagios_download_dir }}"
        creates: "{{ nagios_src }}"
        remote_src: yes
    - name: Run Nagios autoconf
      shell: ./configure --with-httpd-conf=/etc/apache2/sites-enabled
      args:
        chdir: "{{ nagios_src }}"
        creates: "{{ nagios_src }}/Makefile"

